<a href="https://colab.research.google.com/github/SarthoPramanik1075/Deep-Learning/blob/main/Loan_data(DL_ass03).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [3]:
df.shape

(569, 33)

In [4]:
df.isnull().sum()

,0
id,0
diagnosis,0
radius_mean,0
texture_mean,0
perimeter_mean,0
area_mean,0
smoothness_mean,0
compactness_mean,0
concavity_mean,0
concave points_mean,0


In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


#Train Test Split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=.2)

In [7]:
y_train.shape

(455,)

In [8]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [9]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [10]:
encoder= LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test= encoder.transform(y_test)

In [11]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [12]:
len(df.columns)

31

In [13]:
len(X_train)

455

In [14]:
len(X_test)

114

In [15]:
len(y_train)

455

In [16]:
len(y_test)

114

In [17]:
len(X_train) + len(X_test)

569

In [18]:
X_train

array([[-1.49398888, -0.89658212, -1.45622344, ..., -1.02179362,
        -0.74210764, -0.50819753],
       [-0.48426744,  1.1582349 , -0.34072126, ...,  1.61340786,
         2.31065539,  6.93271897],
       [ 0.88006863, -0.51445826,  0.84851958, ...,  1.07688339,
         0.37028634, -0.12718506],
       ...,
       [-0.80280044, -1.21622033, -0.83968625, ..., -1.57670887,
        -0.23015359, -1.09200695],
       [-0.25311959, -1.3219653 , -0.26616328, ..., -0.35136602,
        -0.26491591, -0.57020982],
       [ 1.79620338,  0.39398716,  1.86447455, ...,  1.5191741 ,
         0.27389993, -0.43110116]])

In [19]:
y_train

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,

In [20]:
y_test

array([0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0])

#Numpy Array to tensor

In [21]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

/tmp/ipykernel_7899/351712353.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_7899/351712353.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_7899/351712353.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_7899/351712353.py:12: UserWarning: To copy construct from a tensor, it is recommend

##DATASET && DATALOADER

In [22]:
from torch.utils.data import Dataset, DataLoader

In [23]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features= features
    self.labels= labels
  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [24]:
train_dataset= CustomDataset(X_train_tensor, y_train_tensor)
test_dataset= CustomDataset(X_test_tensor, y_test_tensor)

In [25]:
len(train_dataset)

455

In [26]:
train_dataset[2]

(tensor([ 0.8801, -0.5145,  0.8485,  0.7554,  0.3018, -0.0081,  0.4708,  0.8873,
         -0.0104, -0.9203, -0.3474, -0.6683, -0.3292, -0.1588, -0.7808, -0.5762,
         -0.2753,  0.1240, -0.7924, -0.5232,  0.7226, -0.0772,  0.6929,  0.5766,
          0.4083, -0.0664,  0.3381,  1.0769,  0.3703, -0.1272]),
 tensor(1.))

##DataLoader

In [27]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

#Just Check

In [28]:
X_train.shape[1]

30

In [29]:
X_train.shape[0]

455

In [30]:
y_train.shape[0]

455

In [31]:
X_test.shape[1]

30

In [32]:
X_test.shape[0]

114

In [33]:
y_test.shape[0]

114

#Define Model

In [34]:
import torch.nn as nn

In [35]:
class MySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid= nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [36]:
torch.rand(30,1)

tensor([[0.7404],
        [0.4244],
        [0.9150],
        [0.6452],
        [0.8515],
        [0.1341],
        [0.7251],
        [0.2692],
        [0.7609],
        [0.2117],
        [0.5628],
        [0.6528],
        [0.4211],
        [0.5803],
        [0.8720],
        [0.6602],
        [0.1749],
        [0.1178],
        [0.6096],
        [0.1950],
        [0.9183],
        [0.3442],
        [0.2586],
        [0.7537],
        [0.3832],
        [0.2189],
        [0.4419],
        [0.7235],
        [0.0601],
        [0.5047]])

In [40]:
learning_rate = 0.1
epochs = 25

In [42]:
loss_function = nn.BCELoss()

In [43]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [44]:
model = MySimpleNN(X_train_tensor.shape[1])

In [45]:
model.parameters()

<generator object Module.parameters at 0x7d99885ddee0>

#Training Pipeline

In [47]:
#Input → Prediction → Loss → Gradient → Update

model= MySimpleNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

for epoch in range(epochs):
  for batch_feature, batch_labels in train_loader:
    #forward pass
    y_pred=model(batch_feature)

    #loss function
    loss= loss_function(y_pred, batch_labels.reshape(-1,1))

    #zero grad
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  print(f"{epoch+1}. Loss = {loss.item()}")

1. Loss = 0.16030395030975342
2. Loss = 0.23424364626407623
3. Loss = 0.15347878634929657
4. Loss = 0.06189974769949913
5. Loss = 0.051416438072919846
6. Loss = 0.14574487507343292
7. Loss = 0.019058244302868843
8. Loss = 0.07008986175060272
9. Loss = 0.021016882732510567
10. Loss = 0.017416823655366898
11. Loss = 0.10204519331455231
12. Loss = 0.04565059766173363
13. Loss = 0.13896943628787994
14. Loss = 0.24471643567085266
15. Loss = 0.11327766627073288
16. Loss = 0.011660809628665447
17. Loss = 0.022720875218510628
18. Loss = 0.11025585234165192
19. Loss = 0.021657796576619148
20. Loss = 0.17619238793849945
21. Loss = 0.1575055569410324
22. Loss = 0.03627956658601761
23. Loss = 0.009012030437588692
24. Loss = 0.06287019699811935
25. Loss = 0.03029431216418743


#Training Pipeline version 2

In [56]:
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

batch_size=32
n_sample= len(X_train_tensor)

for epoch in range(epochs):
  for start_indx in range(0, n_sample, batch_size):
    end_indx = start_indx + batch_size
    print(f"{epoch+1}.Start index {start_indx}, end index {end_indx}")
    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred=model(X_batch)

    #loss
    loss= loss_function(y_pred, y_batch.reshape(-1,1))

    #zero grad
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()

  print(f"{epoch+1}. Loss = {loss.item()}")

1.Start index 0, end index 32
1.Start index 32, end index 64
1.Start index 64, end index 96
1.Start index 96, end index 128
1.Start index 128, end index 160
1.Start index 160, end index 192
1.Start index 192, end index 224
1.Start index 224, end index 256
1.Start index 256, end index 288
1.Start index 288, end index 320
1.Start index 320, end index 352
1.Start index 352, end index 384
1.Start index 384, end index 416
1.Start index 416, end index 448
1.Start index 448, end index 480
1. Loss = 0.11730791628360748
2.Start index 0, end index 32
2.Start index 32, end index 64
2.Start index 64, end index 96
2.Start index 96, end index 128
2.Start index 128, end index 160
2.Start index 160, end index 192
2.Start index 192, end index 224
2.Start index 224, end index 256
2.Start index 256, end index 288
2.Start index 288, end index 320
2.Start index 320, end index 352
2.Start index 352, end index 384
2.Start index 384, end index 416
2.Start index 416, end index 448
2.Start index 448, end index 

In [58]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5654047131538391


In [59]:
y_pred.shape

torch.Size([114, 1])

In [60]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9548611044883728


In [61]:
accuracy_list

[0.96875, 0.96875, 0.9375, 0.9444444179534912]

In [62]:
!pip install torchinfo

In [64]:
from torchinfo import summary
summary(model, input_size = (455,30))

Layer (type:depth-idx)                   Output Shape              Param #
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06