<a href="https://colab.research.google.com/github/SarthoPramanik1075/Deep-Learning/blob/main/LSTM_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 !pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [3]:
document = """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""


In [4]:
# NLTK does NOT come with pretrained tokenizers by default.

# Tokenization
nltk.download('punkt')
# Some newer NLTK versions require additional tokenizer tables.
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

##Tokenize

In [5]:
tokens=word_tokenize(document.lower())
tokens

['the',
 'last',
 'train',
 'journey',
 'on',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'the',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'a',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'the',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'he',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

#Build Vocabs

In [6]:
Counter(tokens)

Counter({'the': 55,
         'last': 2,
         'train': 14,
         'journey': 4,
         'on': 4,
         'a': 16,
         'cold': 2,
         'winter': 4,
         'evening': 1,
         ',': 19,
         'daniel': 11,
         'arrived': 1,
         'at': 3,
         'old': 2,
         'railway': 1,
         'station': 5,
         'carrying': 1,
         'small': 3,
         'leather': 1,
         'bag': 2,
         '.': 39,
         'was': 7,
         'nearly': 1,
         'empty': 2,
         'except': 1,
         'for': 4,
         'few': 3,
         'passengers': 3,
         'waiting': 1,
         'quietly': 1,
         'wooden': 1,
         'benches': 1,
         'loud': 1,
         'whistle': 1,
         'echoed': 1,
         'through': 3,
         'air': 3,
         'as': 8,
         'final': 1,
         'of': 6,
         'night': 2,
         'slowly': 3,
         'entered': 2,
         'platform': 2,
         'checked': 1,
         'ticket': 1,
         'in': 1,
      

In [7]:
Counter(tokens).keys()

dict_keys(['the', 'last', 'train', 'journey', 'on', 'a', 'cold', 'winter', 'evening', ',', 'daniel', 'arrived', 'at', 'old', 'railway', 'station', 'carrying', 'small', 'leather', 'bag', '.', 'was', 'nearly', 'empty', 'except', 'for', 'few', 'passengers', 'waiting', 'quietly', 'wooden', 'benches', 'loud', 'whistle', 'echoed', 'through', 'air', 'as', 'final', 'of', 'night', 'slowly', 'entered', 'platform', 'checked', 'ticket', 'in', 'his', 'pocket', 'and', 'walked', 'toward', 'metal', 'doors', 'opened', 'with', 'creaking', 'sound', 'warm', 'rushed', 'outside', 'inside', 'yellow', 'lights', 'flickered', 'softly', 'above', 'rows', 'seats', 'he', 'chose', 'seat', 'beside', 'window', 'placed', 'carefully', 'near', 'feet', 'began', 'to', 'move', 'city', 'disappeared', 'behind', 'thick', 'clouds', 'fog', 'snow', 'started', 'falling', 'gently', 'while', 'distant', 'mountains', 'appeared', 'under', 'moonlight', 'across', 'aisle', 'sat', 'an', 'elderly', 'woman', 'reading', 'book', 'blue', 'cover

In [8]:
vocab ={ '<unk>' : 0}

In [9]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)
vocab

{'<unk>': 0,
 'the': 1,
 'last': 2,
 'train': 3,
 'journey': 4,
 'on': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'daniel': 11,
 'arrived': 12,
 'at': 13,
 'old': 14,
 'railway': 15,
 'station': 16,
 'carrying': 17,
 'small': 18,
 'leather': 19,
 'bag': 20,
 '.': 21,
 'was': 22,
 'nearly': 23,
 'empty': 24,
 'except': 25,
 'for': 26,
 'few': 27,
 'passengers': 28,
 'waiting': 29,
 'quietly': 30,
 'wooden': 31,
 'benches': 32,
 'loud': 33,
 'whistle': 34,
 'echoed': 35,
 'through': 36,
 'air': 37,
 'as': 38,
 'final': 39,
 'of': 40,
 'night': 41,
 'slowly': 42,
 'entered': 43,
 'platform': 44,
 'checked': 45,
 'ticket': 46,
 'in': 47,
 'his': 48,
 'pocket': 49,
 'and': 50,
 'walked': 51,
 'toward': 52,
 'metal': 53,
 'doors': 54,
 'opened': 55,
 'with': 56,
 'creaking': 57,
 'sound': 58,
 'warm': 59,
 'rushed': 60,
 'outside': 61,
 'inside': 62,
 'yellow': 63,
 'lights': 64,
 'flickered': 65,
 'softly': 66,
 'above': 67,
 'rows': 68,
 'seats': 69,
 'he': 70,
 'chose

In [10]:
len(vocab)

284

#Extract Sentence from data

In [11]:
input_sentences = document.split('\n')
input_sentences

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

In [12]:
def text_to_indices(sentence, vocab):
  numerical_sentences=[]
  for token in sentence:
    # print(token)
    if token in vocab:
      numerical_sentences.append(vocab[token])
    else:
      numerical_sentences.append(vocab['<unk>'])
  return numerical_sentences

In [13]:
input_numerical_sentence=[]
for sentence in input_sentences:
  # print(sentence)
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))
  # print(word_tokenize(sentence.lower()))

In [14]:
input_numerical_sentence


[[1, 2, 3, 4],
 [],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28, 29, 30, 5, 31, 32, 21],
 [6, 33, 34, 35, 36, 1, 37, 38, 1, 39, 3, 40, 1, 41, 42, 43, 1, 44, 21],
 [],
 [11, 45, 1, 46, 47, 48, 49, 50, 51, 52, 1, 3, 21],
 [1, 53, 54, 55, 56, 6, 57, 58, 50, 59, 37, 60, 61, 21],
 [62, 1, 3, 10, 63, 64, 65, 66, 67, 68, 40, 24, 69, 21],
 [],
 [70, 71, 6, 72, 73, 1, 74, 50, 75, 48, 20, 76, 77, 48, 78, 21],
 [38, 1, 3, 79, 80, 81, 10, 1, 82, 64, 42, 83, 84, 85, 86, 40, 87, 21],
 [88, 89, 90, 91, 61, 92, 93, 94, 95, 96, 1, 97, 21],
 [],
 [98, 1, 99, 100, 101, 102, 103, 104, 101, 14, 105, 56, 6, 106, 107, 21],
 [108, 27, 109, 110, 111, 61, 1, 74, 38, 112, 113, 26, 114, 115, 21],
 [11, 116, 6, 117, 118, 119, 120, 121, 122, 123, 6, 18, 124, 21],
 [],
 [125, 126, 127, 10, 1, 3, 128, 13, 6, 129, 16, 130, 131, 132, 133, 134, 21],
 [135, 27, 136, 43, 137, 138, 1, 3, 13, 139, 140, 21],
 [6, 141, 142, 143, 1, 16, 38, 1, 54, 144, 145, 146

In [15]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [16]:
training_sequence

[[1, 2],
 [1, 2, 3],
 [1, 2, 3, 4],
 [5, 6],
 [5, 6, 7],
 [5, 6, 7, 8],
 [5, 6, 7, 8, 9],
 [5, 6, 7, 8, 9, 10],
 [5, 6, 7, 8, 9, 10, 11],
 [5, 6, 7, 8, 9, 10, 11, 12],
 [5, 6, 7, 8, 9, 10, 11, 12, 13],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20],
 [5, 6, 7, 8, 9, 10, 11, 12, 13, 1, 14, 15, 16, 17, 6, 18, 19, 20, 21],
 [1, 16],
 [1, 16, 22],
 [1, 16, 22, 23],
 [1, 16, 22, 23, 24],
 [1, 16, 22, 23, 24, 25],
 [1, 16, 22, 23, 24, 25, 26],
 [1, 16, 22, 23, 24, 25, 26, 6],
 [1, 16, 22, 23, 24, 25, 26, 6, 27],
 [1, 16, 22, 23, 24, 25, 26, 6, 27, 28],
 [1, 16, 22, 23, 24, 2

In [17]:
len(training_sequence)

555

In [18]:
len_list=[]
for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

25

In [19]:
#Logic
# [0]*(max(len_list)-len(sequence))

In [20]:
training_sequence[0]

[1, 2]

In [21]:
padded_training_sequence=[]
for sequence in training_sequence:
  padded_training_sequence.append([0]*(max(len_list)-len(sequence)) + sequence)

In [22]:
len(padded_training_sequence[0])

25

##Tensor Convert

In [23]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [24]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   2,   3,   4],
        ...,
        [  0,   0, 158,  ...,   3,  40,   1],
        [  0, 158, 223,  ...,  40,   1,  41],
        [158, 223,  10,  ...,   1,  41,  21]])

In [25]:
X=padded_training_sequence[:,:-1]

In [26]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        ...,
        [  0,   0, 158,  ...,   2,   3,  40],
        [  0, 158, 223,  ...,   3,  40,   1],
        [158, 223,  10,  ...,  40,   1,  41]])

In [27]:
y=padded_training_sequence[:,-1]

In [28]:
y

tensor([  2,   3,   4,   6,   7,   8,   9,  10,  11,  12,  13,   1,  14,  15,
         16,  17,   6,  18,  19,  20,  21,  16,  22,  23,  24,  25,  26,   6,
         27,  28,  29,  30,   5,  31,  32,  21,  33,  34,  35,  36,   1,  37,
         38,   1,  39,   3,  40,   1,  41,  42,  43,   1,  44,  21,  45,   1,
         46,  47,  48,  49,  50,  51,  52,   1,   3,  21,  53,  54,  55,  56,
          6,  57,  58,  50,  59,  37,  60,  61,  21,   1,   3,  10,  63,  64,
         65,  66,  67,  68,  40,  24,  69,  21,  71,   6,  72,  73,   1,  74,
         50,  75,  48,  20,  76,  77,  48,  78,  21,   1,   3,  79,  80,  81,
         10,   1,  82,  64,  42,  83,  84,  85,  86,  40,  87,  21,  89,  90,
         91,  61,  92,  93,  94,  95,  96,   1,  97,  21,   1,  99, 100, 101,
        102, 103, 104, 101,  14, 105,  56,   6, 106, 107,  21,  27, 109, 110,
        111,  61,   1,  74,  38, 112, 113,  26, 114, 115,  21, 116,   6, 117,
        118, 119, 120, 121, 122, 123,   6,  18, 124,  21, 126, 1

#Custom Dataset & DataLoader

In [29]:
class CustomDataset(Dataset):
  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return len(self.X)

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [30]:
dataset = CustomDataset(X,y)

In [31]:
len(dataset)

555

In [32]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [33]:
for input, output in dataloader:
  print(input)
  # print(output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0, 126, 127, 223],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          16,  22,  18, 243, 244, 245,  56, 246, 247,  50],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 125, 126, 127,  10,   1,   3],
        [  0,   0,   0,   0,   0,   0,   0,   0,  38,   1,   3, 268, 145, 146,
          10,  11, 269,   5,   1,  44, 270,   1, 240, 271],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   1,
          16,  22,  23,  24,  25,  26,   6,  27,  28,  29],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   1, 103],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0, 158, 223,  10,  11, 278,
         281, 282, 139, 283,   8,   4,  50,   1, 172, 171],
        [  0,   0,   0,   0

In [34]:
X.shape

torch.Size([555, 24])

##LSTM Cell

In [35]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150,vocab_size)

  def forward(self,x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_state,final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output


In [36]:
model = LSTMModel(len(vocab))

In [37]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [38]:
model.to(device)

LSTMModel(
  (embedding): Embedding(284, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=284, bias=True)
)

In [39]:
len(vocab)

284

In [40]:
x=nn.Embedding(284, 100)
y= nn.LSTM(100,150,batch_first=True)
z= nn.Linear(150, 284)


In [41]:
dataset[0][0].shape

torch.Size([24])

In [42]:
dataset[0][0]

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [43]:
a=dataset[0][0].unsqueeze(0)
a

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [44]:
x(a).shape

torch.Size([1, 24, 100])

In [45]:
b=x(a)

In [46]:
y(b)

(tensor([[[ 0.0717,  0.1408,  0.0056,  ...,  0.0798,  0.0562, -0.0218],
          [ 0.0944,  0.1641,  0.0046,  ...,  0.1128,  0.0856, -0.0359],
          [ 0.1020,  0.1554, -0.0027,  ...,  0.1286,  0.1014, -0.0462],
          ...,
          [ 0.1154,  0.1220, -0.0516,  ...,  0.1433,  0.1226, -0.0795],
          [ 0.1154,  0.1220, -0.0516,  ...,  0.1433,  0.1226, -0.0795],
          [ 0.0036,  0.0371, -0.1297,  ...,  0.0101, -0.0248, -0.1958]]],
        grad_fn=<TransposeBackward0>),
 (tensor([[[ 0.0036,  0.0371, -0.1297, -0.0125, -0.1615, -0.0372, -0.0432,
            -0.1331, -0.0537,  0.1358,  0.0827, -0.0675, -0.0945,  0.2554,
            -0.1383,  0.0744, -0.4176, -0.0992,  0.0202, -0.2086,  0.0782,
             0.0832, -0.0391, -0.1332, -0.0918,  0.1289,  0.0440,  0.0141,
            -0.0107, -0.1832,  0.0341, -0.1632,  0.0027, -0.1386, -0.1224,
             0.0324, -0.0534, -0.0967, -0.1146, -0.1900, -0.2424, -0.0462,
            -0.1261, -0.1696, -0.1535, -0.0448, -0.0306, -0.04

In [47]:
len(y(b))

2

In [48]:
c,d = y(b)

In [49]:
c.shape

torch.Size([1, 24, 150])

In [50]:
e,f=d

In [51]:
e.shape

torch.Size([1, 1, 150])

In [52]:
f.shape

torch.Size([1, 1, 150])

In [53]:
f_temp = f.squeeze(0).shape

In [54]:
f_temp=f.squeeze(0)

In [55]:
z(f_temp)

tensor([[ 2.5526e-02, -2.8396e-01,  2.2360e-01,  1.5616e-01, -2.6503e-01,
         -9.1192e-03, -1.0013e-01, -3.2212e-02,  4.4848e-03, -1.7324e-01,
         -9.7376e-02,  1.9592e-01, -1.0996e-01, -1.8328e-01, -1.1362e-01,
         -3.8797e-01, -1.2979e-01,  1.9644e-01,  2.2081e-02,  1.8944e-01,
         -6.9776e-02,  2.0705e-01,  7.2516e-02, -4.2222e-02,  8.5513e-02,
          8.9177e-02, -1.7617e-02,  5.8565e-02, -5.2420e-02, -6.1182e-02,
          2.0124e-02,  9.1106e-02, -1.8592e-01, -3.9237e-02,  7.6008e-02,
          1.0519e-01, -7.0638e-02,  2.7093e-01, -5.1695e-02, -1.7642e-01,
          1.7870e-01, -1.5306e-01,  1.4429e-02, -3.6384e-01, -2.7715e-01,
          2.0597e-02, -1.1534e-02,  1.1750e-01, -9.9620e-02, -6.2973e-02,
         -7.4139e-02,  8.4182e-02,  9.3122e-02, -9.7024e-02,  1.8403e-02,
          1.5893e-01,  5.7675e-02, -2.6076e-02, -7.5515e-02,  8.2157e-02,
         -2.2390e-01,  8.5295e-02,  7.1976e-02, -2.4521e-02, -1.0576e-01,
          2.3460e-01,  1.1186e-01,  8.

In [56]:
len(z(f_temp)[0])

284

In [57]:
# for params in model.parameters():
#   print(params)

In [58]:
for batch_x, batch_y in dataloader:
  print(batch_x)
  print(batch_y)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,  88,  89,  90,  91],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0, 238, 239, 240,  10,   1],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,  11,  50, 153, 170, 232, 148, 233],
        [  0,   0,   0,   0,   0,   0,   0,   1,   7,  37,  10, 272, 253,  10,
          50,  93, 273, 274, 275,   6, 276, 277,  70, 278],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          11, 266,  50,  76,  75,   1, 258,  62,  48, 267],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,  38,   1,   3, 268, 145, 146,  10,  11, 269],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38,
           1,   3, 268, 145, 146,  10,  11, 269,   5,   1],
        [  0,   0,   0,   0

#Training Loop

In [59]:
epochs = 50
learning_rate=0.001
criterion = nn.CrossEntropyLoss()

In [60]:
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [61]:
for epoch in range(epochs):
  total_loss=0

  for batch_x, batch_y in dataloader:
    batch_x = batch_x.to(device)
    batch_y = batch_y.to(device)
    optimizer.zero_grad()
    output = model(batch_x)

    loss = criterion(output, batch_y)
    loss.backward()
    optimizer.step()
    total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss={total_loss:.4f}")


Epoch 1, Loss=5.6601
Epoch 1, Loss=11.3038
Epoch 1, Loss=16.9315
Epoch 1, Loss=22.5475
Epoch 1, Loss=28.1641
Epoch 1, Loss=33.8061
Epoch 1, Loss=39.4369
Epoch 1, Loss=45.0746
Epoch 1, Loss=50.7002
Epoch 1, Loss=56.2786
Epoch 1, Loss=61.8641
Epoch 1, Loss=67.4898
Epoch 1, Loss=73.1165
Epoch 1, Loss=78.7160
Epoch 1, Loss=84.3024
Epoch 1, Loss=89.9067
Epoch 1, Loss=95.5069
Epoch 1, Loss=101.1392
Epoch 2, Loss=5.4119
Epoch 2, Loss=10.8361
Epoch 2, Loss=16.3069
Epoch 2, Loss=21.6916
Epoch 2, Loss=27.0296
Epoch 2, Loss=32.3627
Epoch 2, Loss=37.6734
Epoch 2, Loss=43.0308
Epoch 2, Loss=48.3917
Epoch 2, Loss=53.6532
Epoch 2, Loss=58.9516
Epoch 2, Loss=64.2033
Epoch 2, Loss=69.2916
Epoch 2, Loss=74.3932
Epoch 2, Loss=79.8801
Epoch 2, Loss=85.1167
Epoch 2, Loss=90.1227
Epoch 2, Loss=95.8135
Epoch 3, Loss=5.0904
Epoch 3, Loss=10.1394
Epoch 3, Loss=15.2326
Epoch 3, Loss=20.1010
Epoch 3, Loss=24.9879
Epoch 3, Loss=29.6660
Epoch 3, Loss=34.4068
Epoch 3, Loss=39.3832
Epoch 3, Loss=44.0607
Epoch 3, Los

In [75]:
def prediction(model, vocab, text):
  #tokenize
  tokenized_text = word_tokenize(text.lower())

  #print(tokenized_text)

  #numerical indies
  numerical_text = text_to_indices(tokenized_text, vocab)
  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text, dtype= torch.long).unsqueeze(0)
  # print(padded_text)

  output = model(padded_text)
  # print("model's output", output)


  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing index {index}")
  # print("printing the word")

  return text + " " + list(vocab.keys())[index]

In [85]:
prediction(model, vocab, "On a cold winter")

'On a cold winter evening'

In [ ]:
document.split('\n')

['The Last Train Journey',
 '',
 'On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.',
 'The station was nearly empty except for a few passengers waiting quietly on wooden benches.',
 'A loud whistle echoed through the air as the final train of the night slowly entered the platform.',
 '',
 'Daniel checked the ticket in his pocket and walked toward the train.',
 'The metal doors opened with a creaking sound and warm air rushed outside.',
 'Inside the train, yellow lights flickered softly above rows of empty seats.',
 '',
 'He chose a seat beside the window and placed his bag carefully near his feet.',
 'As the train began to move, the city lights slowly disappeared behind thick clouds of fog.',
 'Snow started falling gently outside while distant mountains appeared under the moonlight.',
 '',
 'Across the aisle sat an elderly woman reading an old book with a blue cover.',
 'Every few minutes she looked outside the window as if searching for

#Generate automatically

In [89]:
import time
num_tokens = 10
input_text = "daniel checked the ticket"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text

daniel checked the ticket in
daniel checked the ticket in his
daniel checked the ticket in his pocket
daniel checked the ticket in his pocket and
daniel checked the ticket in his pocket and walked
daniel checked the ticket in his pocket and walked toward
daniel checked the ticket in his pocket and walked toward the
daniel checked the ticket in his pocket and walked toward the train
daniel checked the ticket in his pocket and walked toward the train .
daniel checked the ticket in his pocket and walked toward the train . .


#Accuracy Calculation


In [98]:
def calculate_accuracy(model, vocab, text):
  model.eval()

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      batch_x = batch_x.to(device)
      batch_y = batch_y.to(device)

      output = model(batch_x)

      _, predicted = torch.max(output, dim=1)
      # print("printing predicted", predicted)

      correct += (predicted == batch_y).sum().item()
      # print(correct)

      total += batch_y.size(0)
      # print(total)

  accuracy = correct / total
  return accuracy


In [99]:
accuracy= calculate_accuracy(model, dataloader, device)
print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 0.97%
