<a href="https://colab.research.google.com/github/SarthoPramanik1075/Deep-Learning/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.10.0+cpu


In [5]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Device name: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not availabe")

GPU is not availabe


##Creating Tensor

In [17]:
a= torch.empty(2,3)
print(a)
a.shape

tensor([[1.3593e-43, 1.4013e-44, 1.3593e-43],
        [6.4460e-44, 1.6115e-43, 1.4574e-43]])


torch.Size([2, 3])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [19]:
x=torch.tensor([ [1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068936043060538678, 3617861884435903536, 6500727504967840558]])

In [24]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [25]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [27]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [28]:
x*2

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

In [29]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [36]:
torch.manual_seed(100)
p=torch.rand(2,3)
q=torch.rand(2,3)
p
q

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [38]:
p+q

tensor([[0.3744, 0.8587, 0.4706],
        [0.6019, 0.7982, 1.4895]])

In [39]:
p-q

tensor([[-0.1510,  0.7730,  0.0545],
        [ 0.3658,  0.5548,  0.0183]])

In [40]:
p*q

tensor([[0.0293, 0.0350, 0.0546],
        [0.0571, 0.0823, 0.5546]])

In [41]:
p%q

tensor([[0.1117, 0.0019, 0.0545],
        [0.0117, 0.0680, 0.0183]])

In [43]:
c = torch.tensor( [-1,-2,-3,-4])

In [44]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [45]:
d=torch.tensor([1,2,3,4])

In [47]:
torch.neg(d)

tensor([-1, -2, -3, -4])

In [48]:
e=torch.tensor([1.2,2.454,3.4,4.0])

In [50]:
torch.round(e)

tensor([1., 2., 3., 4.])

In [51]:
torch.ceil(d)

tensor([1, 2, 3, 4])

In [52]:
torch.floor(d)

tensor([1, 2, 3, 4])

In [53]:
d=torch.tensor([100,200,300,400])

In [56]:
torch.clamp(d, min=1, max=2)

tensor([2, 2, 2, 2])

In [57]:
f=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
f

tensor([[8., 8., 4.],
        [4., 1., 0.]])

In [59]:
torch.sum(f)

tensor(25.)

In [60]:
torch.sum(f,dim=0)

tensor([12.,  9.,  4.])

In [61]:
torch.sum(f,dim=1)

tensor([20.,  5.])

In [58]:
torch.mean(f)

tensor(4.1667)

In [62]:
torch.median(f)

tensor(4.)

In [65]:
torch.max(f)


tensor(8.)

In [66]:
torch.min(f)

tensor(0.)

In [67]:
torch.prod(f)

tensor(0.)

In [68]:
torch.std(f)

tensor(3.3714)

In [69]:
torch.var(f)

tensor(11.3667)

In [71]:
torch.argmax(f)

tensor(0)

In [72]:
torch.argmin(f)

tensor(5)

In [76]:
g=torch.randint(size=(2,3), low=0, high=10, dtype=torch.int64)
h=torch.randint(size=(3,2), low=0, high=10, dtype=torch.int64)
print(g)
print(h)

torch.matmul(g,h)


tensor([[7, 7, 8],
        [3, 6, 1]])
tensor([[5, 5],
        [0, 4],
        [3, 8]])


tensor([[ 59, 127],
        [ 18,  47]])

In [78]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
torch.dot(vector1, vector2)

tensor(11)

In [79]:
i= torch.tensor([10,20,30])
torch.log(i)

tensor([2.3026, 2.9957, 3.4012])

In [80]:
torch.exp(i)

tensor([2.2026e+04, 4.8517e+08, 1.0686e+13])

In [81]:
torch.sqrt(i)

tensor([3.1623, 4.4721, 5.4772])

In [82]:
torch.sigmoid(i)

tensor([1.0000, 1.0000, 1.0000])

In [87]:
torch.softmax(i, dim=0)

NotImplementedError: "softmax_lastdim_kernel_impl" not implemented for 'Long'

In [89]:
torch.relu(i)

tensor([10, 20, 30])

In [90]:
j=torch.tensor([1,2,3])

In [91]:
k=j.clone()
k

tensor([1, 2, 3])